export interface Country {
  code: string;
  name: string;
  stateLabel: string;
  cityLabel: string;
  hasPostalCode: boolean;
  postalCodeLabel: string;
}

export interface StateData {
  code: string;
  name: string;
  cities: string[];
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afganistán",                    stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "AL", name: "Albania",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "DE", name: "Alemania",                       stateLabel: "Estado Federal",         cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AD", name: "Andorra",                        stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AO", name: "Angola",                         stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "AG", name: "Antigua y Barbuda",              stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SA", name: "Arabia Saudita",                 stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "DZ", name: "Argelia",                        stateLabel: "Wilaya",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AR", name: "Argentina",                      stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AM", name: "Armenia",                        stateLabel: "Marz",                   cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AU", name: "Australia",                      stateLabel: "Estado / Territorio",    cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Postal Code" },
  { code: "AT", name: "Austria",                        stateLabel: "Estado Federal",         cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AZ", name: "Azerbaiyán",                    stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BS", name: "Bahamas",                        stateLabel: "Isla",                   cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BD", name: "Bangladés",                     stateLabel: "División",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BB", name: "Barbados",                       stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BH", name: "Baréin",                        stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BE", name: "Bélgica",                       stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BZ", name: "Belice",                         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BJ", name: "Benín",                         stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BY", name: "Bielorrusia",                    stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BO", name: "Bolivia",                        stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BA", name: "Bosnia y Herzegovina",           stateLabel: "Entidad",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BW", name: "Botsuana",                       stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BR", name: "Brasil",                         stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "CEP" },
  { code: "BN", name: "Brunéi",                        stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BG", name: "Bulgaria",                       stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "BF", name: "Burkina Faso",                   stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BI", name: "Burundi",                        stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "BT", name: "Bután",                         stateLabel: "Dzongkhag",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CV", name: "Cabo Verde",                     stateLabel: "Isla",                   cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "KH", name: "Camboya",                        stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CM", name: "Camerún",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CA", name: "Canadá",                         stateLabel: "Provincia / Territorio", cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Postal Code" },
  { code: "QA", name: "Catar",                          stateLabel: "Municipio",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TD", name: "Chad",                           stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CL", name: "Chile",                          stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CN", name: "China",                          stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CY", name: "Chipre",                         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CO", name: "Colombia",                       stateLabel: "Departamento",           cityLabel: "Ciudad / Municipio", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "KM", name: "Comoras",                        stateLabel: "Isla",                   cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CG", name: "Congo (República del)",          stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CD", name: "Congo (República Democrática)", stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "KP", name: "Corea del Norte",                stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "KR", name: "Corea del Sur",                  stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CI", name: "Costa de Marfil",                stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CR", name: "Costa Rica",                     stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "HR", name: "Croacia",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CU", name: "Cuba",                           stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "DK", name: "Dinamarca",                      stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "DM", name: "Dominica",                       stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "EC", name: "Ecuador",                        stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "EG", name: "Egipto",                         stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "SV", name: "El Salvador",                    stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "AE", name: "Emiratos Árabes Unidos",        stateLabel: "Emirato",                cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "ER", name: "Eritrea",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SK", name: "Eslovaquia",                     stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "SI", name: "Eslovenia",                      stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "ES", name: "España",                         stateLabel: "Comunidad Autónoma",     cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "US", name: "Estados Unidos",                 stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "ZIP Code" },
  { code: "EE", name: "Estonia",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "ET", name: "Etiopía",                       stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "PH", name: "Filipinas",                      stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "FI", name: "Finlandia",                      stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "FJ", name: "Fiyi",                           stateLabel: "División",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "FR", name: "Francia",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "GA", name: "Gabón",                         stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GM", name: "Gambia",                         stateLabel: "División",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GE", name: "Georgia",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "GH", name: "Ghana",                          stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GD", name: "Granada",                        stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GR", name: "Grecia",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "GT", name: "Guatemala",                      stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "GN", name: "Guinea",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GQ", name: "Guinea Ecuatorial",              stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GW", name: "Guinea-Bisáu",                  stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "GY", name: "Guyana",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "HT", name: "Haití",                         stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "HN", name: "Honduras",                       stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "HU", name: "Hungría",                       stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "IN", name: "India",                          stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "PIN Code" },
  { code: "ID", name: "Indonesia",                      stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "IQ", name: "Irak",                           stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "IR", name: "Irán",                          stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "IE", name: "Irlanda",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "IS", name: "Islandia",                       stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MH", name: "Islas Marshall",                 stateLabel: "Atolón",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SB", name: "Islas Salomón",                  stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "IL", name: "Israel",                         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "IT", name: "Italia",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "JM", name: "Jamaica",                        stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "JP", name: "Japón",                         stateLabel: "Prefectura",             cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "JO", name: "Jordania",                       stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "KZ", name: "Kazajistán",                    stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "KE", name: "Kenia",                          stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "KG", name: "Kirguistán",                    stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "KI", name: "Kiribati",                       stateLabel: "Isla",                   cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "KW", name: "Kuwait",                         stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LA", name: "Laos",                           stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "LS", name: "Lesoto",                         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LV", name: "Letonia",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "LB", name: "Líbano",                        stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LR", name: "Liberia",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LY", name: "Libia",                          stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LI", name: "Liechtenstein",                  stateLabel: "Municipio",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "LT", name: "Lituania",                       stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "LU", name: "Luxemburgo",                     stateLabel: "Cantón",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MK", name: "Macedonia del Norte",            stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MG", name: "Madagascar",                     stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MY", name: "Malasia",                        stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MW", name: "Malaui",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MV", name: "Maldivas",                       stateLabel: "Atolón",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "ML", name: "Malí",                          stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MT", name: "Malta",                          stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MA", name: "Marruecos",                      stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MU", name: "Mauricio",                       stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MR", name: "Mauritania",                     stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MX", name: "México",                         stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "FM", name: "Micronesia",                     stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MD", name: "Moldavia",                       stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MC", name: "Mónaco",                        stateLabel: "Barrio",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MN", name: "Mongolia",                       stateLabel: "Aimag",                  cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "ME", name: "Montenegro",                     stateLabel: "Municipio",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "MZ", name: "Mozambique",                     stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "MM", name: "Myanmar",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "NA", name: "Namibia",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "NR", name: "Nauru",                          stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "NP", name: "Nepal",                          stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "NI", name: "Nicaragua",                      stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "NE", name: "Níger",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "NG", name: "Nigeria",                        stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "NO", name: "Noruega",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "NZ", name: "Nueva Zelanda",                  stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Postal Code" },
  { code: "OM", name: "Omán",                          stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "NL", name: "Países Bajos",                  stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "PK", name: "Pakistán",                      stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "PW", name: "Palaos",                         stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "PS", name: "Palestina",                      stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "PA", name: "Panamá",                         stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "PG", name: "Papúa Nueva Guinea",            stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "PY", name: "Paraguay",                       stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "PE", name: "Perú",                          stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "PL", name: "Polonia",                        stateLabel: "Voivodato",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "PT", name: "Portugal",                       stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "PR", name: "Puerto Rico",                    stateLabel: "Municipio",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "ZIP Code" },
  { code: "GB", name: "Reino Unido",                    stateLabel: "Condado / Región",       cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CF", name: "República Centroafricana",       stateLabel: "Prefectura",             cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "CZ", name: "República Checa",                stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "DO", name: "República Dominicana",           stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "RW", name: "Ruanda",                         stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "RO", name: "Rumanía",                       stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "RU", name: "Rusia",                          stateLabel: "Sujeto Federal",         cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "WS", name: "Samoa",                          stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "KN", name: "San Cristóbal y Nieves",        stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SM", name: "San Marino",                     stateLabel: "Municipio",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "VC", name: "San Vicente y las Granadinas",   stateLabel: "Parroquia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LC", name: "Santa Lucía",                   stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "ST", name: "Santo Tomé y Príncipe",         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SN", name: "Senegal",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "RS", name: "Serbia",                         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "SC", name: "Seychelles",                     stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SL", name: "Sierra Leona",                   stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SG", name: "Singapur",                       stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "SY", name: "Siria",                          stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SO", name: "Somalia",                        stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "LK", name: "Sri Lanka",                      stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "ZA", name: "Sudáfrica",                     stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "SD", name: "Sudán",                         stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SS", name: "Sudán del Sur",                  stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "SE", name: "Suecia",                         stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "CH", name: "Suiza",                          stateLabel: "Cantón",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "SR", name: "Surinam",                        stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TH", name: "Tailandia",                      stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "TW", name: "Taiwán",                        stateLabel: "Condado",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "TZ", name: "Tanzania",                       stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TJ", name: "Tayikistán",                    stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "TL", name: "Timor Oriental",                 stateLabel: "Municipio",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TG", name: "Togo",                           stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TO", name: "Tonga",                          stateLabel: "División",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TT", name: "Trinidad y Tobago",              stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "TN", name: "Túnez",                         stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "TM", name: "Turkmenistán",                  stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "TR", name: "Turquía",                       stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "TV", name: "Tuvalu",                         stateLabel: "Atolón",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "UA", name: "Ucrania",                        stateLabel: "Óblast",                cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "UG", name: "Uganda",                         stateLabel: "Distrito",               cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "UY", name: "Uruguay",                        stateLabel: "Departamento",           cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "UZ", name: "Uzbekistán",                    stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "VU", name: "Vanuatu",                        stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "VA", name: "Vaticano",                       stateLabel: "—",                      cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "VE", name: "Venezuela",                      stateLabel: "Estado",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "VN", name: "Vietnam",                        stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: true,  postalCodeLabel: "Código Postal" },
  { code: "YE", name: "Yemen",                          stateLabel: "Gobernación",            cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "DJ", name: "Yibuti",                         stateLabel: "Región",                 cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "ZM", name: "Zambia",                         stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
  { code: "ZW", name: "Zimbabue",                       stateLabel: "Provincia",              cityLabel: "Ciudad", hasPostalCode: false, postalCodeLabel: "Código Postal" },
];

export const STATES_BY_COUNTRY: Record<string, StateData[]> = {
  CO: [
    { code: "AMA", name: "Amazonas",                  cities: ["Leticia", "Puerto Nariño"] },
    { code: "ANT", name: "Antioquia",                 cities: ["Medellín", "Bello", "Itagüí", "Envigado", "Sabaneta", "Rionegro", "Apartadó", "Turbo", "Caucasia"] },
    { code: "ARA", name: "Arauca",                    cities: ["Arauca", "Saravena", "Tame"] },
    { code: "ATL", name: "Atlántico",                 cities: ["Barranquilla", "Soledad", "Malambo", "Baranoa"] },
    { code: "BOL", name: "Bolívar",                   cities: ["Cartagena", "Magangué", "Mompós"] },
    { code: "BOY", name: "Boyacá",                    cities: ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá"] },
    { code: "CAL", name: "Caldas",                    cities: ["Manizales", "Villamaría", "La Dorada", "Riosucio"] },
    { code: "CAQ", name: "Caquetá",                   cities: ["Florencia", "San Vicente del Caguán"] },
    { code: "CAS", name: "Casanare",                  cities: ["Yopal", "Aguazul", "Villanueva"] },
    { code: "CAU", name: "Cauca",                     cities: ["Popayán", "Puerto Tejada", "Santander de Quilichao"] },
    { code: "CES", name: "Cesar",                     cities: ["Valledupar", "Aguachica", "Bosconia"] },
    { code: "CHO", name: "Chocó",                     cities: ["Quibdó", "Istmina"] },
    { code: "COR", name: "Córdoba",                   cities: ["Montería", "Cereté", "Lorica", "Sahagún"] },
    { code: "CUN", name: "Cundinamarca",              cities: ["Soacha", "Fusagasugá", "Facatativá", "Zipaquirá", "Girardot", "Chía", "Mosquera"] },
    { code: "DC",  name: "Bogotá D.C.",               cities: ["Bogotá"] },
    { code: "GUA", name: "Guainía",                   cities: ["Inírida"] },
    { code: "GUV", name: "Guaviare",                  cities: ["San José del Guaviare"] },
    { code: "HUI", name: "Huila",                     cities: ["Neiva", "Pitalito", "Garzón", "La Plata"] },
    { code: "LAG", name: "La Guajira",                cities: ["Riohacha", "Maicao", "Uribia"] },
    { code: "MAG", name: "Magdalena",                 cities: ["Santa Marta", "Ciénaga", "Fundación"] },
    { code: "MET", name: "Meta",                      cities: ["Villavicencio", "Acacías", "Granada"] },
    { code: "NAR", name: "Nariño",                    cities: ["Pasto", "Tumaco", "Ipiales", "La Unión"] },
    { code: "NSA", name: "Norte de Santander",        cities: ["Cúcuta", "Ocaña", "Pamplona", "Tibú"] },
    { code: "PUT", name: "Putumayo",                  cities: ["Mocoa", "Puerto Asís"] },
    { code: "QUI", name: "Quindío",                   cities: ["Armenia", "Calarcá", "La Tebaida"] },
    { code: "RIS", name: "Risaralda",                 cities: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"] },
    { code: "SAP", name: "San Andrés y Providencia",  cities: ["San Andrés", "Providencia"] },
    { code: "SAN", name: "Santander",                 cities: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil"] },
    { code: "SUC", name: "Sucre",                     cities: ["Sincelejo", "Corozal", "Sampués"] },
    { code: "TOL", name: "Tolima",                    cities: ["Ibagué", "Espinal", "Melgar", "Honda"] },
    { code: "VAC", name: "Valle del Cauca",           cities: ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago", "Jamundí"] },
    { code: "VAU", name: "Vaupés",                    cities: ["Mitú"] },
    { code: "VID", name: "Vichada",                   cities: ["Puerto Carreño"] },
  ],
  VE: [
    { code: "AN", name: "Anzoátegui",      cities: ["Barcelona", "Puerto La Cruz"] },
    { code: "AP", name: "Apure",           cities: ["San Fernando de Apure"] },
    { code: "AR", name: "Aragua",          cities: ["Maracay", "La Victoria"] },
    { code: "BA", name: "Barinas",         cities: ["Barinas"] },
    { code: "BO", name: "Bolívar",         cities: ["Ciudad Bolívar", "Ciudad Guayana"] },
    { code: "CA", name: "Carabobo",        cities: ["Valencia", "Guacara"] },
    { code: "CO", name: "Cojedes",         cities: ["San Carlos"] },
    { code: "DA", name: "Delta Amacuro",   cities: ["Tucupita"] },
    { code: "DC", name: "Distrito Capital",cities: ["Caracas"] },
    { code: "FA", name: "Falcón",          cities: ["Coro", "Punto Fijo"] },
    { code: "GU", name: "Guárico",         cities: ["San Juan de los Morros", "Calabozo"] },
    { code: "LA", name: "Lara",            cities: ["Barquisimeto", "Carora"] },
    { code: "ME", name: "Mérida",          cities: ["Mérida"] },
    { code: "MI", name: "Miranda",         cities: ["Los Teques", "Guarenas", "Petare"] },
    { code: "MO", name: "Monagas",         cities: ["Maturín"] },
    { code: "NE", name: "Nueva Esparta",   cities: ["La Asunción", "Porlamar"] },
    { code: "PO", name: "Portuguesa",      cities: ["Guanare", "Acarigua"] },
    { code: "SU", name: "Sucre",           cities: ["Cumaná", "Carúpano"] },
    { code: "TA", name: "Táchira",         cities: ["San Cristóbal", "Táriba"] },
    { code: "TR", name: "Trujillo",        cities: ["Trujillo", "Valera"] },
    { code: "VA", name: "Vargas",          cities: ["La Guaira"] },
    { code: "YA", name: "Yaracuy",         cities: ["San Felipe"] },
    { code: "ZU", name: "Zulia",           cities: ["Maracaibo", "Cabimas"] },
  ],
  EC: [
    { code: "A",  name: "Azuay",           cities: ["Cuenca", "Gualaceo"] },
    { code: "B",  name: "Bolívar",         cities: ["Guaranda"] },
    { code: "C",  name: "Carchi",          cities: ["Tulcán"] },
    { code: "D",  name: "Orellana",        cities: ["Francisco de Orellana"] },
    { code: "E",  name: "Esmeraldas",      cities: ["Esmeraldas"] },
    { code: "F",  name: "Cañar",           cities: ["Azogues", "Cañar"] },
    { code: "G",  name: "Guayas",          cities: ["Guayaquil", "Samborondón", "Daule", "Milagro"] },
    { code: "H",  name: "Chimborazo",      cities: ["Riobamba", "Alausí"] },
    { code: "I",  name: "Imbabura",        cities: ["Ibarra", "Otavalo"] },
    { code: "J",  name: "Loja",            cities: ["Loja", "Catamayo"] },
    { code: "L",  name: "Cotopaxi",        cities: ["Latacunga", "La Maná"] },
    { code: "M",  name: "Manabí",          cities: ["Portoviejo", "Manta", "Chone"] },
    { code: "N",  name: "Napo",            cities: ["Tena"] },
    { code: "O",  name: "El Oro",          cities: ["Machala", "Pasaje"] },
    { code: "P",  name: "Pichincha",       cities: ["Quito", "Rumiñahui", "Cayambe"] },
    { code: "R",  name: "Los Ríos",        cities: ["Babahoyo", "Quevedo"] },
    { code: "S",  name: "Morona Santiago", cities: ["Macas"] },
    { code: "T",  name: "Tungurahua",      cities: ["Ambato", "Baños"] },
    { code: "U",  name: "Sucumbíos",       cities: ["Nueva Loja"] },
    { code: "W",  name: "Galápagos",       cities: ["Puerto Ayora"] },
    { code: "X",  name: "Pastaza",         cities: ["Puyo"] },
    { code: "Y",  name: "Zamora Chinchipe",cities: ["Zamora"] },
    { code: "Z",  name: "Santa Elena",     cities: ["Santa Elena", "La Libertad"] },
  ],
  PE: [
    { code: "AMA", name: "Amazonas",       cities: ["Chachapoyas"] },
    { code: "ANC", name: "Áncash",         cities: ["Huaraz", "Chimbote"] },
    { code: "APU", name: "Apurímac",       cities: ["Abancay"] },
    { code: "ARE", name: "Arequipa",       cities: ["Arequipa", "Camaná"] },
    { code: "AYA", name: "Ayacucho",       cities: ["Ayacucho"] },
    { code: "CAJ", name: "Cajamarca",      cities: ["Cajamarca", "Jaén"] },
    { code: "CAL", name: "Callao",         cities: ["Callao"] },
    { code: "CUS", name: "Cusco",          cities: ["Cusco", "Sicuani"] },
    { code: "HUC", name: "Huánuco",        cities: ["Huánuco"] },
    { code: "HUV", name: "Huancavelica",   cities: ["Huancavelica"] },
    { code: "ICA", name: "Ica",            cities: ["Ica", "Pisco", "Nazca"] },
    { code: "JUN", name: "Junín",          cities: ["Huancayo", "Tarma"] },
    { code: "LAL", name: "La Libertad",    cities: ["Trujillo", "Pacasmayo"] },
    { code: "LAM", name: "Lambayeque",     cities: ["Chiclayo", "Lambayeque"] },
    { code: "LIM", name: "Lima",           cities: ["Lima", "Miraflores", "San Isidro", "Surco", "Ate", "San Juan de Lurigancho"] },
    { code: "LOR", name: "Loreto",         cities: ["Iquitos"] },
    { code: "MDD", name: "Madre de Dios",  cities: ["Puerto Maldonado"] },
    { code: "MOQ", name: "Moquegua",       cities: ["Moquegua"] },
    { code: "PAS", name: "Pasco",          cities: ["Cerro de Pasco"] },
    { code: "PIU", name: "Piura",          cities: ["Piura", "Sullana", "Talara"] },
    { code: "PUN", name: "Puno",           cities: ["Puno", "Juliaca"] },
    { code: "SAM", name: "San Martín",     cities: ["Tarapoto", "Moyobamba"] },
    { code: "TAC", name: "Tacna",          cities: ["Tacna"] },
    { code: "TUM", name: "Tumbes",         cities: ["Tumbes"] },
    { code: "UCA", name: "Ucayali",        cities: ["Pucallpa"] },
  ],
  MX: [
    { code: "AGU", name: "Aguascalientes",      cities: ["Aguascalientes"] },
    { code: "BCN", name: "Baja California",     cities: ["Tijuana", "Mexicali", "Ensenada"] },
    { code: "BCS", name: "Baja California Sur", cities: ["La Paz", "Los Cabos"] },
    { code: "CAM", name: "Campeche",            cities: ["Campeche", "Ciudad del Carmen"] },
    { code: "CHP", name: "Chiapas",             cities: ["Tuxtla Gutiérrez", "San Cristóbal de las Casas"] },
    { code: "CHH", name: "Chihuahua",           cities: ["Chihuahua", "Ciudad Juárez"] },
    { code: "CMX", name: "Ciudad de México",    cities: ["Ciudad de México"] },
    { code: "COA", name: "Coahuila",            cities: ["Saltillo", "Torreón", "Monclova"] },
    { code: "COL", name: "Colima",              cities: ["Colima", "Manzanillo"] },
    { code: "DUR", name: "Durango",             cities: ["Durango", "Gómez Palacio"] },
    { code: "GUA", name: "Guanajuato",          cities: ["León", "Guanajuato", "Irapuato", "Celaya"] },
    { code: "GRO", name: "Guerrero",            cities: ["Acapulco", "Chilpancingo"] },
    { code: "HID", name: "Hidalgo",             cities: ["Pachuca", "Tulancingo"] },
    { code: "JAL", name: "Jalisco",             cities: ["Guadalajara", "Zapopan", "Tlaquepaque"] },
    { code: "MEX", name: "Estado de México",    cities: ["Ecatepec", "Naucalpan", "Toluca", "Nezahualcóyotl"] },
    { code: "MIC", name: "Michoacán",           cities: ["Morelia", "Uruapan", "Zamora"] },
    { code: "MOR", name: "Morelos",             cities: ["Cuernavaca", "Jiutepec"] },
    { code: "NAY", name: "Nayarit",             cities: ["Tepic", "Bahía de Banderas"] },
    { code: "NLE", name: "Nuevo León",          cities: ["Monterrey", "Guadalupe", "San Nicolás de los Garza"] },
    { code: "OAX", name: "Oaxaca",              cities: ["Oaxaca", "Juchitán"] },
    { code: "PUE", name: "Puebla",              cities: ["Puebla", "Tehuacán"] },
    { code: "QUE", name: "Querétaro",           cities: ["Querétaro", "San Juan del Río"] },
    { code: "ROO", name: "Quintana Roo",        cities: ["Cancún", "Playa del Carmen", "Chetumal"] },
    { code: "SLP", name: "San Luis Potosí",     cities: ["San Luis Potosí", "Ciudad Valles"] },
    { code: "SIN", name: "Sinaloa",             cities: ["Culiacán", "Mazatlán", "Los Mochis"] },
    { code: "SON", name: "Sonora",              cities: ["Hermosillo", "Ciudad Obregón", "Nogales"] },
    { code: "TAB", name: "Tabasco",             cities: ["Villahermosa", "Cárdenas"] },
    { code: "TAM", name: "Tamaulipas",          cities: ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico"] },
    { code: "TLA", name: "Tlaxcala",            cities: ["Tlaxcala", "Apizaco"] },
    { code: "VER", name: "Veracruz",            cities: ["Veracruz", "Xalapa", "Coatzacoalcos"] },
    { code: "YUC", name: "Yucatán",             cities: ["Mérida", "Valladolid"] },
    { code: "ZAC", name: "Zacatecas",           cities: ["Zacatecas", "Fresnillo"] },
  ],
  AR: [
    { code: "BA", name: "Buenos Aires",         cities: ["Buenos Aires", "Mar del Plata", "La Plata", "Bahía Blanca", "Quilmes", "Lanús"] },
    { code: "CA", name: "Catamarca",            cities: ["San Fernando del Valle de Catamarca"] },
    { code: "CH", name: "Chaco",                cities: ["Resistencia", "Barranqueras"] },
    { code: "CT", name: "Chubut",               cities: ["Rawson", "Comodoro Rivadavia", "Puerto Madryn"] },
    { code: "CB", name: "Córdoba",              cities: ["Córdoba", "Villa María", "Río Cuarto"] },
    { code: "CR", name: "Corrientes",           cities: ["Corrientes", "Goya"] },
    { code: "ER", name: "Entre Ríos",           cities: ["Paraná", "Concordia"] },
    { code: "FO", name: "Formosa",              cities: ["Formosa"] },
    { code: "JY", name: "Jujuy",                cities: ["San Salvador de Jujuy", "Palpalá"] },
    { code: "LP", name: "La Pampa",             cities: ["Santa Rosa"] },
    { code: "LR", name: "La Rioja",             cities: ["La Rioja"] },
    { code: "MZ", name: "Mendoza",              cities: ["Mendoza", "San Rafael", "Godoy Cruz"] },
    { code: "MN", name: "Misiones",             cities: ["Posadas", "Oberá"] },
    { code: "NQ", name: "Neuquén",              cities: ["Neuquén", "San Martín de los Andes"] },
    { code: "RN", name: "Río Negro",            cities: ["Viedma", "Bariloche", "Cipolletti"] },
    { code: "SA", name: "Salta",                cities: ["Salta", "Tartagal"] },
    { code: "SJ", name: "San Juan",             cities: ["San Juan"] },
    { code: "SL", name: "San Luis",             cities: ["San Luis", "Villa Mercedes"] },
    { code: "SC", name: "Santa Cruz",           cities: ["Río Gallegos", "El Calafate"] },
    { code: "SF", name: "Santa Fe",             cities: ["Santa Fe", "Rosario", "Rafaela"] },
    { code: "SE", name: "Santiago del Estero",  cities: ["Santiago del Estero", "La Banda"] },
    { code: "TF", name: "Tierra del Fuego",     cities: ["Ushuaia", "Río Grande"] },
    { code: "TU", name: "Tucumán",              cities: ["San Miguel de Tucumán", "Concepción"] },
  ],
  CL: [
    { code: "AI", name: "Aysén",                cities: ["Coyhaique", "Puerto Aysén"] },
    { code: "AN", name: "Antofagasta",          cities: ["Antofagasta", "Calama"] },
    { code: "AP", name: "Arica y Parinacota",   cities: ["Arica", "Putre"] },
    { code: "AR", name: "La Araucanía",         cities: ["Temuco", "Villarrica", "Pucón"] },
    { code: "AT", name: "Atacama",              cities: ["Copiapó", "Vallenar"] },
    { code: "BI", name: "Biobío",               cities: ["Concepción", "Los Ángeles"] },
    { code: "CO", name: "Coquimbo",             cities: ["La Serena", "Coquimbo"] },
    { code: "LI", name: "O'Higgins",            cities: ["Rancagua", "San Fernando"] },
    { code: "LL", name: "Los Lagos",            cities: ["Puerto Montt", "Osorno", "Castro"] },
    { code: "LR", name: "Los Ríos",             cities: ["Valdivia", "La Unión"] },
    { code: "MA", name: "Magallanes",           cities: ["Punta Arenas", "Puerto Natales"] },
    { code: "ML", name: "Maule",                cities: ["Talca", "Curicó", "Linares"] },
    { code: "NB", name: "Ñuble",                cities: ["Chillán", "San Carlos"] },
    { code: "RM", name: "Metropolitana",        cities: ["Santiago", "Puente Alto", "Las Condes", "Maipú"] },
    { code: "TA", name: "Tarapacá",             cities: ["Iquique", "Alto Hospicio"] },
    { code: "VS", name: "Valparaíso",           cities: ["Valparaíso", "Viña del Mar", "Quilpué"] },
  ],
  PA: [
    { code: "BO", name: "Bocas del Toro",       cities: ["Bocas del Toro", "Almirante"] },
    { code: "CC", name: "Coclé",                cities: ["Penonomé", "Aguadulce"] },
    { code: "CL", name: "Colón",                cities: ["Colón", "Portobelo"] },
    { code: "CH", name: "Chiriquí",             cities: ["David", "Bugaba"] },
    { code: "DA", name: "Darién",               cities: ["La Palma", "Metetí"] },
    { code: "HE", name: "Herrera",              cities: ["Chitré", "Ocú"] },
    { code: "LS", name: "Los Santos",           cities: ["Las Tablas", "Los Santos"] },
    { code: "PA", name: "Panamá",               cities: ["Ciudad de Panamá", "San Miguelito", "Tocumen"] },
    { code: "VE", name: "Veraguas",             cities: ["Santiago"] },
    { code: "PO", name: "Panamá Oeste",         cities: ["La Chorrera", "Arraiján"] },
  ],
  US: [
    { code: "AL", name: "Alabama",              cities: ["Birmingham", "Montgomery", "Huntsville"] },
    { code: "AK", name: "Alaska",               cities: ["Anchorage", "Fairbanks"] },
    { code: "AZ", name: "Arizona",              cities: ["Phoenix", "Tucson", "Scottsdale"] },
    { code: "AR", name: "Arkansas",             cities: ["Little Rock", "Fort Smith"] },
    { code: "CA", name: "California",           cities: ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "San Jose"] },
    { code: "CO", name: "Colorado",             cities: ["Denver", "Colorado Springs", "Aurora"] },
    { code: "CT", name: "Connecticut",          cities: ["Bridgeport", "New Haven", "Hartford"] },
    { code: "DE", name: "Delaware",             cities: ["Wilmington", "Dover"] },
    { code: "FL", name: "Florida",              cities: ["Miami", "Orlando", "Tampa", "Jacksonville"] },
    { code: "GA", name: "Georgia",              cities: ["Atlanta", "Augusta", "Savannah"] },
    { code: "HI", name: "Hawaii",               cities: ["Honolulu", "Hilo"] },
    { code: "ID", name: "Idaho",                cities: ["Boise", "Meridian"] },
    { code: "IL", name: "Illinois",             cities: ["Chicago", "Aurora", "Rockford"] },
    { code: "IN", name: "Indiana",              cities: ["Indianapolis", "Fort Wayne"] },
    { code: "IA", name: "Iowa",                 cities: ["Des Moines", "Cedar Rapids"] },
    { code: "KS", name: "Kansas",               cities: ["Wichita", "Overland Park"] },
    { code: "KY", name: "Kentucky",             cities: ["Louisville", "Lexington"] },
    { code: "LA", name: "Louisiana",            cities: ["New Orleans", "Baton Rouge"] },
    { code: "ME", name: "Maine",                cities: ["Portland", "Bangor"] },
    { code: "MD", name: "Maryland",             cities: ["Baltimore", "Frederick"] },
    { code: "MA", name: "Massachusetts",        cities: ["Boston", "Worcester", "Springfield"] },
    { code: "MI", name: "Michigan",             cities: ["Detroit", "Grand Rapids"] },
    { code: "MN", name: "Minnesota",            cities: ["Minneapolis", "Saint Paul"] },
    { code: "MS", name: "Mississippi",          cities: ["Jackson", "Gulfport"] },
    { code: "MO", name: "Missouri",             cities: ["Kansas City", "Saint Louis"] },
    { code: "MT", name: "Montana",              cities: ["Billings", "Missoula"] },
    { code: "NE", name: "Nebraska",             cities: ["Omaha", "Lincoln"] },
    { code: "NV", name: "Nevada",               cities: ["Las Vegas", "Reno"] },
    { code: "NH", name: "New Hampshire",        cities: ["Manchester", "Nashua"] },
    { code: "NJ", name: "New Jersey",           cities: ["Newark", "Jersey City", "Paterson"] },
    { code: "NM", name: "New Mexico",           cities: ["Albuquerque", "Las Cruces"] },
    { code: "NY", name: "New York",             cities: ["New York City", "Buffalo", "Albany"] },
    { code: "NC", name: "North Carolina",       cities: ["Charlotte", "Raleigh", "Greensboro"] },
    { code: "ND", name: "North Dakota",         cities: ["Fargo", "Bismarck"] },
    { code: "OH", name: "Ohio",                 cities: ["Columbus", "Cleveland", "Cincinnati"] },
    { code: "OK", name: "Oklahoma",             cities: ["Oklahoma City", "Tulsa"] },
    { code: "OR", name: "Oregon",               cities: ["Portland", "Salem", "Eugene"] },
    { code: "PA", name: "Pennsylvania",         cities: ["Philadelphia", "Pittsburgh", "Allentown"] },
    { code: "RI", name: "Rhode Island",         cities: ["Providence", "Cranston"] },
    { code: "SC", name: "South Carolina",       cities: ["Columbia", "Charleston"] },
    { code: "SD", name: "South Dakota",         cities: ["Sioux Falls", "Rapid City"] },
    { code: "TN", name: "Tennessee",            cities: ["Nashville", "Memphis", "Knoxville"] },
    { code: "TX", name: "Texas",                cities: ["Houston", "San Antonio", "Dallas", "Austin"] },
    { code: "UT", name: "Utah",                 cities: ["Salt Lake City", "West Valley City"] },
    { code: "VT", name: "Vermont",              cities: ["Burlington", "Montpelier"] },
    { code: "VA", name: "Virginia",             cities: ["Virginia Beach", "Norfolk", "Chesapeake"] },
    { code: "WA", name: "Washington",           cities: ["Seattle", "Spokane", "Tacoma"] },
    { code: "WV", name: "West Virginia",        cities: ["Charleston", "Huntington"] },
    { code: "WI", name: "Wisconsin",            cities: ["Milwaukee", "Madison"] },
    { code: "WY", name: "Wyoming",              cities: ["Cheyenne", "Casper"] },
  ],
  ES: [
    { code: "AN", name: "Andalucía",            cities: ["Sevilla", "Málaga", "Córdoba", "Granada", "Almería"] },
    { code: "AR", name: "Aragón",               cities: ["Zaragoza", "Huesca", "Teruel"] },
    { code: "AS", name: "Asturias",             cities: ["Oviedo", "Gijón", "Avilés"] },
    { code: "CB", name: "Cantabria",            cities: ["Santander", "Torrelavega"] },
    { code: "CL", name: "Castilla y León",      cities: ["Valladolid", "Burgos", "Salamanca", "León"] },
    { code: "CM", name: "Castilla-La Mancha",   cities: ["Albacete", "Ciudad Real", "Toledo", "Guadalajara"] },
    { code: "CT", name: "Cataluña",             cities: ["Barcelona", "Tarragona", "Lleida", "Girona"] },
    { code: "EX", name: "Extremadura",          cities: ["Badajoz", "Cáceres", "Mérida"] },
    { code: "GA", name: "Galicia",              cities: ["Vigo", "A Coruña", "Ourense", "Santiago de Compostela"] },
    { code: "IB", name: "Islas Baleares",       cities: ["Palma", "Ibiza", "Mahón"] },
    { code: "IC", name: "Islas Canarias",       cities: ["Las Palmas de Gran Canaria", "Santa Cruz de Tenerife"] },
    { code: "LR", name: "La Rioja",             cities: ["Logroño"] },
    { code: "MD", name: "Madrid",               cities: ["Madrid", "Alcalá de Henares", "Getafe", "Leganés"] },
    { code: "MU", name: "Murcia",               cities: ["Murcia", "Cartagena"] },
    { code: "NA", name: "Navarra",              cities: ["Pamplona", "Tudela"] },
    { code: "PV", name: "País Vasco",           cities: ["Bilbao", "San Sebastián", "Vitoria-Gasteiz"] },
    { code: "VC", name: "Comunitat Valenciana", cities: ["Valencia", "Alicante", "Castellón"] },
  ],
};
